### ISSUE TITLE
运行demo.py时报错

### ISSUE THREAD

**Issue by chenwuxing** [yxlijun/S3FD.pytorch#10]
![tim 20190226212558](https://user-images.githubusercontent.com/41286936/53415840-2a4a2980-3a0d-11e9-8394-b7e8ec9cd3ab.png)
已经下载了readme提供的人脸模型，放置在根目录下的weights目录下
![tim 20190226212859](https://user-images.githubusercontent.com/41286936/53416039-9331a180-3a0d-11e9-80b7-3b7afecb59ed.png)
作者可以帮我看下哪里出错了么，谢谢了

**Comment by LeileiCao** [comment]
python3运行时,需要在__init__.py文件detection前加点: from .detection import Detect

**Comment by chenwuxing** [comment]
ok,我去试试，感谢您的回复




发自网易邮箱大师
在2019年2月28日 19:14，Leilei Cao<notifications@github.com> 写道：

python3运行时,需要在__init__.py文件detection前加点.
