### ISSUE TITLE
加载vgg16预训练模型权重报错

### ISSUE THREAD

**Issue by chenwuxing** [yxlijun/S3FD.pytorch#13]
作者你好，我在运行train.py时程序在加载vgg16预训练模型权重时报错
![@9DIG XB%IR@J6MMDP0YE8E](https://user-images.githubusercontent.com/41286936/55461187-68e38d00-5626-11e9-9beb-29473631bc56.png)
我已经从pytorch官方的github地址下载了vgg16的预训练模型，将其放置在指定的weights文件下
![TIM截图20190403154012](https://user-images.githubusercontent.com/41286936/55461536-3a19e680-5627-11e9-914e-9cfb7015cbd2.png)
现在不知道如何下手，希望您能指导一下，谢谢您了

**Comment by yxlijun** [comment]
您好，加载这个预训练模型是不对的，你可以下载模型在https://pan.baidu.com/s/1Q-YqoxJyqvln6KTcIck1tQ

**Comment by chenwuxing** [comment]
好的，感谢您的回复
