### ISSUE TITLE
How to solve these problems in MATLAB when I plot the curves ?

### ISSUE THREAD

**Issue by sagittahjz** [yxlijun/S3FD.pytorch#19]
I ran wider_test.py and got a folder —— s3fd_val in eval_tools.
Then I ran wider_eval.m in MATLAB, but some errors were reported.

---------------------------------------------------------------------------------

错误使用 legend (line 273)
未知的属性 'show'

出错 plot_pr (line 22)
legend1 = legend(lendge_name,'show');

出错 wider_plot (line 33)
    plot_pr(propose, recall, name_list, seting_class, set_list{i},dateset_class);

出错 wider_eval (line 35)
wider_plot(setting_name_list,dir_int,seting_class,dateset_class);

--------------------------------------------------------------------------------

**Comment by sagittahjz** [comment]
> I ran wider_test.py and got a folder —— s3fd_val in eval_tools.
> Then I ran wider_eval.m in MATLAB, but some errors were reported.
> 
> 错误使用 legend (line 273)
> 未知的属性 'show'
> 
> 出错 plot_pr (line 22)
> legend1 = legend(lendge_name,'show');
> 
> 出错 wider_plot (line 33)
> plot_pr(propose, recall, name_list, seting_class, set_list{i},dateset_class);
> 
> 出错 wider_eval (line 35)
> wider_plot(setting_name_list,dir_int,seting_class,dateset_class);

comment out ‘show’ can solve the problems

**Comment by chenwuxing** [comment]
同学，请问下你运行完wider_test.py产生s3fd_val文件夹，然后在运行wider_eval.m文件就可以产生模型的测试准确率图了么
