### ISSUE TITLE
wider face ap

### ISSUE THREAD

**Issue by ciw-ws** [yxlijun/S3FD.pytorch#2]
Hi, glad to see your update. 
I saw this issue a few days ago, did you figure out what way the key?
https://github.com/sfzhang15/SFD/issues/57

**Comment by yxlijun** [comment]
I find the wider face test way  have a little problem,and change some data augmentation

**Comment by ciw-ws** [comment]
Thanks

**Comment by luuuyi** [comment]
作者你好，我按照论文复现出来发现hard上的结果也是比较低，请问下你解决问题的方法是什么

**Comment by yxlijun** [comment]
你可以检查一下你的测试方法了，是否用了多尺度测试

**Comment by luuuyi** [comment]
@yxlijun 我用了你的训练代码，发现测试demo时如果阈值设为文章里面说的0.05，那么的确会出现很多False Positive的人脸检测框，影响性能。但是多尺度测试时好像用了box vote的方法。所以我的疑问是论文里面那个指标是在thre为0.05然后多尺度时测出来的么？你上文中说的改了一部分data augmentation的方法，具体是什么？谢谢了

**Comment by yxlijun** [comment]
用了data anchor sampling,跑demo的时候阈值肯定要设高一点，但是我们在测试精度的时候，需要将阈值设 低一点，因为它求的是pr曲线下面的面积，当阈值设低一点，并不影响整个检测性能

**Comment by luuuyi** [comment]
@ciw-ws 好的 感谢解答，所以最终论文那个指标是multi-size test+box vote的结果么？我看论文里面没有提到测试的时候用多尺度测试

**Comment by yxlijun** [comment]
是用了多尺度测试，论文开放了测试代码，他里面用到了多尺度

**Comment by luuuyi** [comment]
@ciw-ws 好的 感谢回复
