### ISSUE TITLE
What should be modified in data/config.py? Can't find file "wider_face_train_bbx_gt.txt"

### ISSUE THREAD

**Issue by TomTHChen** [yxlijun/S3FD.pytorch#33]
HI. I am trying to run the code.
Which parts in config.py should be modified?
Error when running prepare_wider_data.py, can not find text file "wider_face_train_bbx_gt.txt".
What is this file and where can I obtain it.
Thank you.

**Comment by yxlijun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yxlijun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
