### ISSUE TITLE
Downloading checkpoints

### ISSUE THREAD

**Issue by sushil-bharati** [yxlijun/S3FD.pytorch#7]
I am finding it real hard to download checkpoint files from the website you uploaded in as I do not understand Chinese.
Is there any other way you can share them? Much appreciated. Thanks.

**Comment by sushil-bharati** [comment]
我发现很难从您上传的网站下载检查点文件，因为我不懂中文。
还有其他方法可以分享吗？非常感激。谢谢。

**Comment by yxlijun** [comment]
you can download face model in https://drive.google.com/open?id=1Dyr-s3mAQEj-AXCz8YIIYt6Zl3JpjFQ7

**Comment by Benuraj** [comment]
Hi can you provide the hand model as well

**Comment by yxlijun** [comment]
hand model can downloaded in readme

**Comment by Benuraj** [comment]
Somehow the Baidu link is very confusing. I'm unable to get the pth file downloading. If you can provide any alternate link that would be of great help.

**Comment by yxlijun** [comment]
you can download hand model in https://drive.google.com/file/d/1KgTgIOyG1czrCqOJAgFAsaoJF_5hHJdy/view?usp=sharing
