### ISSUE TITLE
Questions about facemodel

### ISSUE THREAD

**Issue by piddnad** [yxlijun/S3FD.pytorch#9]
Hi, I have downloaded your ''face model'' which is provided in README, and successfully run it on my machine. But now I still have some questions because it seems works well on faces but not work well on heads.
Here is my question: Is the "face model" trained with both head dataset "SCUT-HEAD" and face dataset "widerface", or just only trained with face dataset "widerface"?

**Comment by yxlijun** [comment]
the face model is just only trained with the wideface ,you can train yourself head detector with  "SCUT-HEAD"

**Comment by piddnad** [comment]
@yxlijun Thanks! 
I have prepared the SCUT-HEAD dataset and started training using
```
python train.py --batch_size 4 --dataset head
```
but unfortunately something is wrong and I get this error message:
```
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    train()
  File "train.py", line 161, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/kxy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kxy/S3FD.pytorch/layers/modules/multibox_loss.py", line 125, in forward
    loss_l /= N
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #3 'other'
```
It seems that codes in this line make the error:``loss_l, loss_c = criterion(out, targets)``, but I have checked that the data type of "out" and "targets" is both "float32".
Can you help me with this?
PS. My PyTorch version is 0.4.1.

**Comment by yxlijun** [comment]
you can try .float() in wrong location

**Comment by YueXiNPU** [comment]
@yxlijun I am sorry. I met the same question. What do you mean by .float()?

**Comment by piddnad** [comment]
@YueXiNPU Hi, have you solved this question now?

**Comment by piddnad** [comment]
I have solved this problem by edit code in layers/modules/multibox_loss.py
change line 124
```
N = num_pos.data.sum() if num_pos.data.sum() > 0 else num
```
to
```
N = num_pos.data.sum().float() if num_pos.data.sum() > 0 else num.float()
```

**Comment by jsprieto10** [comment]
How do you transform the Dataset Data into the the expect by the prepare.py file?

**Comment by piddnad** [comment]
> How do you transform the Dataset Data into the the expect by the prepare.py file?

I only trained the head model using SCUT-HEAD dataset, by coverting the dataset to PASCAL VOC format.

**Comment by jsprieto10** [comment]
¿How did you do that? ¿Do you if the process that you used to convert that SCUT-HEAD into pascal voc could be the same with the hands dataset?

**Comment by piddnad** [comment]
I write a script to convert the head dataset, and don't know whether the process is the same between head dataset and hand dataset..

**Comment by jsprieto10** [comment]
Can you send me that script? or make a gist?

**Comment by piddnad** [comment]
You can refer to this: https://github.com/cizhenshi/ObjectDetection/blob/master/ToVoc.py
